sudo: false
language: node_js

node_js:
# Other Google Node.js libs are dropping or haved dropped support for 0.10 and 0.12
#  - "0.10"
#  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"

cache:
  yarn: true
  directories:
  - node_modules/

before_install:
  - npm i -g nyc codecov

after_success:
  - nyc report --reporter=lcov > coverage.lcov && codecov
