on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please-pr:
    runs-on: ubuntu-latest
    steps:
      - id: release-pr
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.FORKING_TOKEN }}
          release-type: node
          fork: true
          package-name: googleapis
          command: release-pr
      - id: label
        uses: actions/github-script@v3    
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const latestRelease = await github.issues.addLabels({
                owner,
                repo,
                issue_number: ${{steps.release-please.outputs.pr}},
                labels: ['autorelease: pending']
              });
              console.log(`Tagged ${{steps.release-pr.outputs.pr}}`)
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: tag-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: googleapis
          command: github-release
      - uses: actions/setup-node@v1
        if: ${{ steps.tag-release.outputs.release_created }}
        with:
          node-version: 14
          registry-url: 'https://wombat-dressing-room.appspot.com/'
      - run: |
          npm install
          npm publish
        if: ${{ steps.tag-release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
