on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: npm install
      - run: npm run update-disclaimers
      - run: gh repo fork googleapis/google-api-nodejs-client --fork-name google-api-nodejs-client-autodisco --clone --remote
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run submit-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODE_BOT_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
